repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: ruff check --fix
        language: python
        types_or: [python, pyi]
      - id: ruff-format
        name: ruff format
        entry: ruff format
        language: python
        types_or: [python, pyi]
